### ISSUE TITLE
[BUG]'mujoco.structs.MjModelGeomViews' object has no attribute 'name

### ISSUE THREAD

**Issue by kilimization** [PKU-MARL/omnisafe#10]
## Describe the bug

'mujoco.structs.MjModelGeomViews' object has no attribute 'name'

When I run `examples/vis_safety_gymnasium.py`, the bugs as follows,
```
"/home/saferl/Documents/github/omnisafe/omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/world.py", line 435, in init
    self.geom_names = [
  File "/home/saferl/Documents/github/omnisafe/omnisafe/envs/Safety_Gymnasium/safety_gymnasium/envs/safety_gym_v2/world.py", line 438, in <listcomp>
    if self.model.geom(i).name != 'floor'
AttributeError: 'mujoco.structs.MjModelGeomViews' object has no attribute 'name'
```
My virtual environment depends on 
```
Gymnasium           0.26.3
mujoco                  2.2.0
numpy                   1.23.5
torch                      1.10.0+cu111
torchaudio             0.10.0+rocm4.1
torchvision             0.11.0+cu111
```
## Checklist

- [x] I have checked that there is no similar issue in the repo. (**required**)
- [x] I have read the [documentation](https://omnisafe.readthedocs.io). (**required**)
- [x] I have provided a minimal working example to reproduce the bug. (**required**)

**Comment by wfei1** [comment]
It seems that the version of mujoco is not consistent. I installed and was able to run properly using the mujoco==2.3.0.

**Comment by zmsn-2077** [comment]
The latest Gymnasium 0.26.3 relies on 2.2.0[1], but Mujoco is currently updated to 2.3.0 [2]. In order to be closer to the Gymnasium community, we have now reduced the Mujoco version to 2.2.0. Mujoco==2.2.0 currently works fine after testing, you can pull the latest code and try it.
[1] https://github.com/Farama-Foundation/Gymnasium/blob/main/setup.py#L41
[2] https://github.com/deepmind/mujoco/releases/tag/2.3.0

**Comment by yinglinmonian** [comment]
I also encountered this problem in using this repo and just needed to downgrade mujoco to 2.2.0.
